//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMEF
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/", ConfigurationName="ServiceMEF.WsmefperucomprasWs")]
    public interface WsmefperucomprasWs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rConsultaCCP")]
        System.Threading.Tasks.Task<ServiceMEF.consultaCcpOutputForm> consultaCCPAsync(string pAnoEje, string pSecEjec, string pCertificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rAnularOCE")]
        System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> anularOCEAsync(ServiceMEF.anulacionOceInputForm envioOceInputForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rFinGeneracionOCE")]
        System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> finGeneracionOCEAsync(string pAnoEje, string pSecEjec, string pCeamRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rClasificadorCEAM")]
        System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> clasificadorCEAMAsync(ServiceMEF.clasificadorCeamInputForm envioOceInputForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rReservaCCP")]
        System.Threading.Tasks.Task<ServiceMEF.reservaCcpOutputForm> reservaCCPAsync(ServiceMEF.reservaCcpInputForm pReservaCcpInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rAnularReservaCCP")]
        System.Threading.Tasks.Task<ServiceMEF.anularReservaOutputForm> anularReservaCCPAsync(string pAnoEje, string pSecEjec, string pCeamRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rEnvioOCE")]
        System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> envioOCEAsync(ServiceMEF.envioOceInputForm envioOceInputForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rEstadoOCE")]
        System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> estadoOCEAsync(ServiceMEF.estadoOceInputForm estadoOceInputForm);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class consultaCcpOutputForm
    {
        
        private certificadoDto[] certificadoSecuenciaField;
        
        private string codRptaField;
        
        private string mensajeRptaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certificadoSecuencia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public certificadoDto[] certificadoSecuencia
        {
            get
            {
                return this.certificadoSecuenciaField;
            }
            set
            {
                this.certificadoSecuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codRpta
        {
            get
            {
                return this.codRptaField;
            }
            set
            {
                this.codRptaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensajeRpta
        {
            get
            {
                return this.mensajeRptaField;
            }
            set
            {
                this.mensajeRptaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class certificadoDto
    {
        
        private long anoEjeField;
        
        private bool anoEjeFieldSpecified;
        
        private long certificadoField;
        
        private bool certificadoFieldSpecified;
        
        private string codDocField;
        
        private certificadoDetDto[] detalleField;
        
        private string fechaDocField;
        
        private string fechaProcesoField;
        
        private string glosaField;
        
        private decimal montoCAField;
        
        private bool montoCAFieldSpecified;
        
        private decimal montoMNField;
        
        private bool montoMNFieldSpecified;
        
        private decimal montoSaldoDisponibleField;
        
        private bool montoSaldoDisponibleFieldSpecified;
        
        private decimal montoSaldoReservaField;
        
        private bool montoSaldoReservaFieldSpecified;
        
        private string nomDocField;
        
        private string nomRubroField;
        
        private string numDocField;
        
        private string rubroField;
        
        private long secEjecField;
        
        private bool secEjecFieldSpecified;
        
        private long secuenciaField;
        
        private bool secuenciaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long anoEje
        {
            get
            {
                return this.anoEjeField;
            }
            set
            {
                this.anoEjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anoEjeSpecified
        {
            get
            {
                return this.anoEjeFieldSpecified;
            }
            set
            {
                this.anoEjeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificadoSpecified
        {
            get
            {
                return this.certificadoFieldSpecified;
            }
            set
            {
                this.certificadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codDoc
        {
            get
            {
                return this.codDocField;
            }
            set
            {
                this.codDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public certificadoDetDto[] detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaDoc
        {
            get
            {
                return this.fechaDocField;
            }
            set
            {
                this.fechaDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaProceso
        {
            get
            {
                return this.fechaProcesoField;
            }
            set
            {
                this.fechaProcesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string glosa
        {
            get
            {
                return this.glosaField;
            }
            set
            {
                this.glosaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal montoCA
        {
            get
            {
                return this.montoCAField;
            }
            set
            {
                this.montoCAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoCASpecified
        {
            get
            {
                return this.montoCAFieldSpecified;
            }
            set
            {
                this.montoCAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal montoMN
        {
            get
            {
                return this.montoMNField;
            }
            set
            {
                this.montoMNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoMNSpecified
        {
            get
            {
                return this.montoMNFieldSpecified;
            }
            set
            {
                this.montoMNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal montoSaldoDisponible
        {
            get
            {
                return this.montoSaldoDisponibleField;
            }
            set
            {
                this.montoSaldoDisponibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSaldoDisponibleSpecified
        {
            get
            {
                return this.montoSaldoDisponibleFieldSpecified;
            }
            set
            {
                this.montoSaldoDisponibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal montoSaldoReserva
        {
            get
            {
                return this.montoSaldoReservaField;
            }
            set
            {
                this.montoSaldoReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSaldoReservaSpecified
        {
            get
            {
                return this.montoSaldoReservaFieldSpecified;
            }
            set
            {
                this.montoSaldoReservaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nomDoc
        {
            get
            {
                return this.nomDocField;
            }
            set
            {
                this.nomDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string nomRubro
        {
            get
            {
                return this.nomRubroField;
            }
            set
            {
                this.nomRubroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string numDoc
        {
            get
            {
                return this.numDocField;
            }
            set
            {
                this.numDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string rubro
        {
            get
            {
                return this.rubroField;
            }
            set
            {
                this.rubroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public long secEjec
        {
            get
            {
                return this.secEjecField;
            }
            set
            {
                this.secEjecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secEjecSpecified
        {
            get
            {
                return this.secEjecFieldSpecified;
            }
            set
            {
                this.secEjecFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public long secuencia
        {
            get
            {
                return this.secuenciaField;
            }
            set
            {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secuenciaSpecified
        {
            get
            {
                return this.secuenciaFieldSpecified;
            }
            set
            {
                this.secuenciaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class certificadoDetDto
    {
        
        private string clasificadorField;
        
        private string idClasificadorField;
        
        private decimal montoCAField;
        
        private bool montoCAFieldSpecified;
        
        private decimal montoMNField;
        
        private bool montoMNFieldSpecified;
        
        private string nomClasificadorField;
        
        private decimal saldoDisponibleField;
        
        private bool saldoDisponibleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clasificador
        {
            get
            {
                return this.clasificadorField;
            }
            set
            {
                this.clasificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idClasificador
        {
            get
            {
                return this.idClasificadorField;
            }
            set
            {
                this.idClasificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal montoCA
        {
            get
            {
                return this.montoCAField;
            }
            set
            {
                this.montoCAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoCASpecified
        {
            get
            {
                return this.montoCAFieldSpecified;
            }
            set
            {
                this.montoCAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal montoMN
        {
            get
            {
                return this.montoMNField;
            }
            set
            {
                this.montoMNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoMNSpecified
        {
            get
            {
                return this.montoMNFieldSpecified;
            }
            set
            {
                this.montoMNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nomClasificador
        {
            get
            {
                return this.nomClasificadorField;
            }
            set
            {
                this.nomClasificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal saldoDisponible
        {
            get
            {
                return this.saldoDisponibleField;
            }
            set
            {
                this.saldoDisponibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saldoDisponibleSpecified
        {
            get
            {
                return this.saldoDisponibleFieldSpecified;
            }
            set
            {
                this.saldoDisponibleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class estadoOceInputForm
    {
        
        private string anoEjeField;
        
        private string ceamOceField;
        
        private string ceamOceSecuenciaField;
        
        private string ceamRequerimientoField;
        
        private string estadoField;
        
        private string motivoEstadoField;
        
        private string secEjecField;
        
        private string usuarioEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anoEje
        {
            get
            {
                return this.anoEjeField;
            }
            set
            {
                this.anoEjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ceamOce
        {
            get
            {
                return this.ceamOceField;
            }
            set
            {
                this.ceamOceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ceamOceSecuencia
        {
            get
            {
                return this.ceamOceSecuenciaField;
            }
            set
            {
                this.ceamOceSecuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ceamRequerimiento
        {
            get
            {
                return this.ceamRequerimientoField;
            }
            set
            {
                this.ceamRequerimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string motivoEstado
        {
            get
            {
                return this.motivoEstadoField;
            }
            set
            {
                this.motivoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string secEjec
        {
            get
            {
                return this.secEjecField;
            }
            set
            {
                this.secEjecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuarioEstado
        {
            get
            {
                return this.usuarioEstadoField;
            }
            set
            {
                this.usuarioEstadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class envioOceDetDto
    {
        
        private string ceamOceSequenciaField;
        
        private string fechaEntregaInicialField;
        
        private string montoField;
        
        private string plazoMaximoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ceamOceSequencia
        {
            get
            {
                return this.ceamOceSequenciaField;
            }
            set
            {
                this.ceamOceSequenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaEntregaInicial
        {
            get
            {
                return this.fechaEntregaInicialField;
            }
            set
            {
                this.fechaEntregaInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string plazoMaximo
        {
            get
            {
                return this.plazoMaximoField;
            }
            set
            {
                this.plazoMaximoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class envioOceInputForm
    {
        
        private string anoEjeField;
        
        private string ceamOceField;
        
        private string ceamRequerimientoField;
        
        private envioOceDetDto[] detalleField;
        
        private string fechaOceField;
        
        private string montoField;
        
        private string rucField;
        
        private string secEjecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anoEje
        {
            get
            {
                return this.anoEjeField;
            }
            set
            {
                this.anoEjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ceamOce
        {
            get
            {
                return this.ceamOceField;
            }
            set
            {
                this.ceamOceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ceamRequerimiento
        {
            get
            {
                return this.ceamRequerimientoField;
            }
            set
            {
                this.ceamRequerimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listDetalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public envioOceDetDto[] detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaOce
        {
            get
            {
                return this.fechaOceField;
            }
            set
            {
                this.fechaOceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ruc
        {
            get
            {
                return this.rucField;
            }
            set
            {
                this.rucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string secEjec
        {
            get
            {
                return this.secEjecField;
            }
            set
            {
                this.secEjecField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class anularReservaOutputForm
    {
        
        private string codRptaField;
        
        private string mensajeRptaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codRpta
        {
            get
            {
                return this.codRptaField;
            }
            set
            {
                this.codRptaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensajeRpta
        {
            get
            {
                return this.mensajeRptaField;
            }
            set
            {
                this.mensajeRptaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class reservaCcp2Dto
    {
        
        private long certificadoField;
        
        private bool certificadoFieldSpecified;
        
        private string mensajeRptaField;
        
        private long secuenciaField;
        
        private bool secuenciaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificadoSpecified
        {
            get
            {
                return this.certificadoFieldSpecified;
            }
            set
            {
                this.certificadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensajeRpta
        {
            get
            {
                return this.mensajeRptaField;
            }
            set
            {
                this.mensajeRptaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long secuencia
        {
            get
            {
                return this.secuenciaField;
            }
            set
            {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secuenciaSpecified
        {
            get
            {
                return this.secuenciaFieldSpecified;
            }
            set
            {
                this.secuenciaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class reservaCcpOutputForm
    {
        
        private string codRptaField;
        
        private reservaCcp2Dto[] listDetalleField;
        
        private string mensajeRptaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codRpta
        {
            get
            {
                return this.codRptaField;
            }
            set
            {
                this.codRptaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listDetalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public reservaCcp2Dto[] listDetalle
        {
            get
            {
                return this.listDetalleField;
            }
            set
            {
                this.listDetalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensajeRpta
        {
            get
            {
                return this.mensajeRptaField;
            }
            set
            {
                this.mensajeRptaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class reservaCcpDto
    {
        
        private long certificadoField;
        
        private bool certificadoFieldSpecified;
        
        private decimal montoReservaField;
        
        private bool montoReservaFieldSpecified;
        
        private long secuenciaField;
        
        private bool secuenciaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificadoSpecified
        {
            get
            {
                return this.certificadoFieldSpecified;
            }
            set
            {
                this.certificadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal montoReserva
        {
            get
            {
                return this.montoReservaField;
            }
            set
            {
                this.montoReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoReservaSpecified
        {
            get
            {
                return this.montoReservaFieldSpecified;
            }
            set
            {
                this.montoReservaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long secuencia
        {
            get
            {
                return this.secuenciaField;
            }
            set
            {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secuenciaSpecified
        {
            get
            {
                return this.secuenciaFieldSpecified;
            }
            set
            {
                this.secuenciaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class reservaCcpInputForm
    {
        
        private string anoEjeField;
        
        private string ceamRequerimientoField;
        
        private reservaCcpDto[] detalleField;
        
        private string secEjecField;
        
        private string tipoReservaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anoEje
        {
            get
            {
                return this.anoEjeField;
            }
            set
            {
                this.anoEjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ceamRequerimiento
        {
            get
            {
                return this.ceamRequerimientoField;
            }
            set
            {
                this.ceamRequerimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public reservaCcpDto[] detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string secEjec
        {
            get
            {
                return this.secEjecField;
            }
            set
            {
                this.secEjecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoReserva
        {
            get
            {
                return this.tipoReservaField;
            }
            set
            {
                this.tipoReservaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class clasificadorCeamInputForm
    {
        
        private string anoEjeField;
        
        private string especificaField;
        
        private string especificaDetField;
        
        private string fechaModificacionIndField;
        
        private string genericaField;
        
        private string idClasificadorField;
        
        private string indUsoCppField;
        
        private string subgenericaField;
        
        private string subgenericaDetField;
        
        private string tipoTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anoEje
        {
            get
            {
                return this.anoEjeField;
            }
            set
            {
                this.anoEjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string especifica
        {
            get
            {
                return this.especificaField;
            }
            set
            {
                this.especificaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string especificaDet
        {
            get
            {
                return this.especificaDetField;
            }
            set
            {
                this.especificaDetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaModificacionInd
        {
            get
            {
                return this.fechaModificacionIndField;
            }
            set
            {
                this.fechaModificacionIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string generica
        {
            get
            {
                return this.genericaField;
            }
            set
            {
                this.genericaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string idClasificador
        {
            get
            {
                return this.idClasificadorField;
            }
            set
            {
                this.idClasificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string indUsoCpp
        {
            get
            {
                return this.indUsoCppField;
            }
            set
            {
                this.indUsoCppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string subgenerica
        {
            get
            {
                return this.subgenericaField;
            }
            set
            {
                this.subgenericaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string subgenericaDet
        {
            get
            {
                return this.subgenericaDetField;
            }
            set
            {
                this.subgenericaDetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tipoTransaccion
        {
            get
            {
                return this.tipoTransaccionField;
            }
            set
            {
                this.tipoTransaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class genericOutputForm
    {
        
        private string codRptaField;
        
        private string mensajeRptaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codRpta
        {
            get
            {
                return this.codRptaField;
            }
            set
            {
                this.codRptaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensajeRpta
        {
            get
            {
                return this.mensajeRptaField;
            }
            set
            {
                this.mensajeRptaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.mefperucompras.mef.gob.pe/")]
    public partial class anulacionOceInputForm
    {
        
        private string anoEjeField;
        
        private string ceamOceField;
        
        private string ceamOceSecuenciaField;
        
        private string ceamRequerimientoField;
        
        private string motivoAnulacionField;
        
        private string secEjecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anoEje
        {
            get
            {
                return this.anoEjeField;
            }
            set
            {
                this.anoEjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ceamOce
        {
            get
            {
                return this.ceamOceField;
            }
            set
            {
                this.ceamOceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ceamOceSecuencia
        {
            get
            {
                return this.ceamOceSecuenciaField;
            }
            set
            {
                this.ceamOceSecuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ceamRequerimiento
        {
            get
            {
                return this.ceamRequerimientoField;
            }
            set
            {
                this.ceamRequerimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string motivoAnulacion
        {
            get
            {
                return this.motivoAnulacionField;
            }
            set
            {
                this.motivoAnulacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string secEjec
        {
            get
            {
                return this.secEjecField;
            }
            set
            {
                this.secEjecField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WsmefperucomprasWsChannel : ServiceMEF.WsmefperucomprasWs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WsmefperucomprasWsClient : System.ServiceModel.ClientBase<ServiceMEF.WsmefperucomprasWs>, ServiceMEF.WsmefperucomprasWs
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsmefperucomprasWsClient() : 
                base(WsmefperucomprasWsClient.GetDefaultBinding(), WsmefperucomprasWsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WsmefperucomprasWsImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsmefperucomprasWsClient(EndpointConfiguration endpointConfiguration) : 
                base(WsmefperucomprasWsClient.GetBindingForEndpoint(endpointConfiguration), WsmefperucomprasWsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsmefperucomprasWsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsmefperucomprasWsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsmefperucomprasWsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsmefperucomprasWsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsmefperucomprasWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.consultaCcpOutputForm> consultaCCPAsync(string pAnoEje, string pSecEjec, string pCertificado)
        {
            return base.Channel.consultaCCPAsync(pAnoEje, pSecEjec, pCertificado);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> anularOCEAsync(ServiceMEF.anulacionOceInputForm envioOceInputForm)
        {
            return base.Channel.anularOCEAsync(envioOceInputForm);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> finGeneracionOCEAsync(string pAnoEje, string pSecEjec, string pCeamRequerimiento)
        {
            return base.Channel.finGeneracionOCEAsync(pAnoEje, pSecEjec, pCeamRequerimiento);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> clasificadorCEAMAsync(ServiceMEF.clasificadorCeamInputForm envioOceInputForm)
        {
            return base.Channel.clasificadorCEAMAsync(envioOceInputForm);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.reservaCcpOutputForm> reservaCCPAsync(ServiceMEF.reservaCcpInputForm pReservaCcpInput)
        {
            return base.Channel.reservaCCPAsync(pReservaCcpInput);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.anularReservaOutputForm> anularReservaCCPAsync(string pAnoEje, string pSecEjec, string pCeamRequerimiento)
        {
            return base.Channel.anularReservaCCPAsync(pAnoEje, pSecEjec, pCeamRequerimiento);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> envioOCEAsync(ServiceMEF.envioOceInputForm envioOceInputForm)
        {
            return base.Channel.envioOCEAsync(envioOceInputForm);
        }
        
        public System.Threading.Tasks.Task<ServiceMEF.genericOutputForm> estadoOCEAsync(ServiceMEF.estadoOceInputForm estadoOceInputForm)
        {
            return base.Channel.estadoOCEAsync(estadoOceInputForm);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsmefperucomprasWsImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsmefperucomprasWsImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://wstest.mineco.gob.pe/wsmefperucomprasapp/webservice/mefperucomprasWs");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsmefperucomprasWsClient.GetBindingForEndpoint(EndpointConfiguration.WsmefperucomprasWsImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsmefperucomprasWsClient.GetEndpointAddress(EndpointConfiguration.WsmefperucomprasWsImplPort);
        }
        
        public enum EndpointConfiguration
        {   
            WsmefperucomprasWsImplPort,
        }
    }
}
